service: <appid>
runtime: nodejs12
env: standard
env_variables:
  PORT: "8080"
  DBHOST: "<dbhost>"
  DBNAME: "<dbname>"
  DBUSER: "<dbuser>"
  DBPASSWORD: "<dbpassword>"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "<appname>"
  APPLICATION_PORT : "8080"
  PROJECT : "<project>"

